# Supply Chain Data Set: Exploratory Analysis and Insights

## Part 1: Data Cleaning and Feature Engineering

Dataset Link: https://www.kaggle.com/datasets/shashwatwork/dataco-smart-supply-chain-for-big-data-analysis

##  Reading Data:

In [1]:
# Importing all header files necessary for the run
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
# Reads the file having the dataset
ds = pd.read_csv('DataCoSupplyChainDataset.csv',header= 0,encoding='unicode_escape')

In [3]:
# prints the first five lines of the read dataset
ds.head()

,Type,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Delivery Status,Late_delivery_risk,Category Id,Category Name,Customer City,...,Order Zipcode,Product Card Id,Product Category Id,Product Description,Product Image,Product Name,Product Price,Product Status,shipping date (DateOrders),Shipping Mode
0,DEBIT,3,4,91.250000,314.640015,Advance shipping,0,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,2/3/2018 22:56,Standard Class
1,TRANSFER,5,4,-249.089996,311.359985,Late delivery,1,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/18/2018 12:27,Standard Class
2,CASH,4,4,-247.779999,309.720001,Shipping on time,0,73,Sporting Goods,San Jose,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/17/2018 12:06,Standard Class
3,DEBIT,3,4,22.860001,304.809998,Advance shipping,0,73,Sporting Goods,Los Angeles,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/16/2018 11:45,Standard Class
4,PAYMENT,2,4,134.210007,298.250000,Advance shipping,0,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/15/2018 11:24,Standard Class

In [4]:
# Display the column names from the dataset
ds.columns

Index(['Type', 'Days for shipping (real)', 'Days for shipment (scheduled)',
       'Benefit per order', 'Sales per customer', 'Delivery Status',
       'Late_delivery_risk', 'Category Id', 'Category Name', 'Customer City',
       'Customer Country', 'Customer Email', 'Customer Fname', 'Customer Id',
       'Customer Lname', 'Customer Password', 'Customer Segment',
       'Customer State', 'Customer Street', 'Customer Zipcode',
       'Department Id', 'Department Name', 'Latitude', 'Longitude', 'Market',
       'Order City', 'Order Country', 'Order Customer Id',
       'order date (DateOrders)', 'Order Id', 'Order Item Cardprod Id',
       'Order Item Discount', 'Order Item Discount Rate', 'Order Item Id',
       'Order Item Product Price', 'Order Item Profit Ratio',
       'Order Item Quantity', 'Sales', 'Order Item Total',
       'Order Profit Per Order', 'Order Region', 'Order State', 'Order Status',
       'Order Zipcode', 'Product Card Id', 'Product Category Id',
       'Product Description', 'Product Image', 'Product Name', 'Product Price',
       'Product Status', 'shipping date (DateOrders)', 'Shipping Mode'],
      dtype='object')

In [5]:
# Checks for duplicates in the dataset
ds.duplicated().sum()

0

In [6]:
# Displays the shape of the dataset
ds.shape

(180519, 53)

In [7]:
# Shows the information about the dataset
ds.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 180519 entries, 0 to 180518
Data columns (total 53 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   Type                           180519 non-null  object
 1   Days for shipping (real)       180519 non-null  int64
 2   Days for shipment (scheduled)  180519 non-null  int64
 3   Benefit per order              180519 non-null  float64
 4   Sales per customer             180519 non-null  float64
 5   Delivery Status                180519 non-null  object
 6   Late_delivery_risk             180519 non-null  int64
 7   Category Id                    180519 non-null  int64
 8   Category Name                  180519 non-null  object
 9   Customer City                  180519 non-null  object
 10  Customer Country               180519 non-null  object
 11  Customer Email                 180519 non-null  object
 12  Customer Fname                 180519 non-null  object
 13  Customer Id                    180519 non-null  int64
 14  Customer Lname                 180511 non-null  object
 15  Customer Password              180519 non-null  object
 16  Customer Segment               180519 non-null  object
 17  Customer State                 180519 non-null  object
 18  Customer Street                180519 non-null  object
 19  Customer Zipcode               180516 non-null  float64
 20  Department Id                  180519 non-null  int64
 21  Department Name                180519 non-null  object
 22  Latitude                       180519 non-null  float64
 23  Longitude                      180519 non-null  float64
 24  Market                         180519 non-null  object
 25  Order City                     180519 non-null  object
 26  Order Country                  180519 non-null  object
 27  Order Customer Id              180519 non-null  int64
 28  order date (DateOrders)        180519 non-null  object
 29  Order Id                       180519 non-null  int64
 30  Order Item Cardprod Id         180519 non-null  int64
 31  Order Item Discount            180519 non-null  float64
 32  Order Item Discount Rate       180519 non-null  float64
 33  Order Item Id                  180519 non-null  int64
 34  Order Item Product Price       180519 non-null  float64
 35  Order Item Profit Ratio        180519 non-null  float64
 36  Order Item Quantity            180519 non-null  int64
 37  Sales                          180519 non-null  float64
 38  Order Item Total               180519 non-null  float64
 39  Order Profit Per Order         180519 non-null  float64
 40  Order Region                   180519 non-null  object
 41  Order State                    180519 non-null  object
 42  Order Status                   180519 non-null  object
 43  Order Zipcode                  24840 non-null   float64
 44  Product Card Id                180519 non-null  int64
 45  Product Category Id            180519 non-null  int64
 46  Product Description            0 non-null       float64
 47  Product Image                  180519 non-null  object
 48  Product Name                   180519 non-null  object
 49  Product Price                  180519 non-null  float64
 50  Product Status                 180519 non-null  int64
 51  shipping date (DateOrders)     180519 non-null  object
 52  Shipping Mode                  180519 non-null  object
dtypes: float64(15), int64(14), object(24)
memory usage: 73.0+ MB

In [8]:
# Shows the correaltion between the column names of the dataset
ds.corr()

,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Late_delivery_risk,Category Id,Customer Id,Customer Zipcode,Department Id,Latitude,...,Order Item Quantity,Sales,Order Item Total,Order Profit Per Order,Order Zipcode,Product Card Id,Product Category Id,Product Description,Product Price,Product Status
Days for shipping (real),1.000000,0.515880,-0.005101,0.001757,0.401415,-0.000348,0.003432,0.000112,-0.001631,-0.004073,...,-0.000811,0.001962,0.001757,-0.005101,-0.000811,-0.000859,-0.000348,NaN,0.002185,NaN
Days for shipment (scheduled),0.515880,1.000000,-0.000185,0.006445,-0.369352,-0.000367,0.000899,-0.003019,-0.000262,-0.005300,...,-0.002925,0.006327,0.006445,-0.000185,0.005249,-0.000431,-0.000367,NaN,0.006912,NaN
Benefit per order,-0.005101,-0.000185,1.000000,0.133484,-0.003727,0.031889,0.009354,0.002235,0.031442,0.000338,...,0.015696,0.131816,0.133484,1.000000,-0.004978,0.033161,0.031889,NaN,0.103459,NaN
Sales per customer,0.001757,0.006445,0.133484,1.000000,-0.003791,0.225201,0.060181,-0.001304,0.232367,-0.000223,...,0.105413,0.989744,1.000000,0.133484,-0.000138,0.236367,0.225201,NaN,0.781781,NaN
Late_delivery_risk,0.401415,-0.369352,-0.003727,-0.003791,1.000000,0.001752,0.001484,0.003148,0.001077,0.000679,...,-0.000139,-0.003564,-0.003791,-0.003727,-0.014131,0.001490,0.001752,NaN,-0.002175,NaN
Category Id,-0.000348,-0.000367,0.031889,0.225201,0.001752,1.000000,0.274633,0.002898,0.888835,0.002195,...,-0.302408,0.227483,0.225201,0.031889,-0.005943,0.991092,1.000000,NaN,0.461059,NaN
Customer Id,0.003432,0.000899,0.009354,0.060181,0.001484,0.274633,1.000000,0.002022,0.136897,0.002335,...,-0.091328,0.060961,0.060181,0.009354,-0.005659,0.228039,0.274633,NaN,0.111118,NaN
Customer Zipcode,0.000112,-0.003019,0.002235,-0.001304,0.003148,0.002898,0.002022,1.000000,0.002878,0.584553,...,-0.006174,-0.001490,-0.001304,0.002235,0.011843,0.003173,0.002898,NaN,0.002191,NaN
Department Id,-0.001631,-0.000262,0.031442,0.232367,0.001077,0.888835,0.136897,0.002878,1.000000,0.002460,...,-0.265437,0.234718,0.232367,0.031442,-0.005982,0.906117,0.888835,NaN,0.446743,NaN
Latitude,-0.004073,-0.005300,0.000338,-0.000223,0.000679,0.002195,0.002335,0.584553,0.002460,1.000000,...,-0.001853,-0.000696,-0.000223,0.000338,-0.002921,0.002031,0.002195,NaN,0.000471,NaN
Longitude,0.003911,0.003675,-0.002521,0.001444,-0.001915,-0.002320,-0.005146,-0.923921,-0.002435,-0.525122,...,0.004467,0.001696,0.001444,-0.002521,-0.005880,-0.002580,-0.002320,NaN,-0.000894,NaN
Order Customer Id,0.003432,0.000899,0.009354,0.060181,0.001484,0.274633,1.000000,0.002022,0.136897,0.002335,...,-0.091328,0.060961,0.060181,0.009354,-0.005659,0.228039,0.274633,NaN,0.111118,NaN
Order Id,-0.001711,-0.001878,0.013716,0.079000,-0.001293,0.198496,0.204821,-0.001210,0.106757,-0.002984,...,-0.087073,0.079835,0.079000,0.013716,0.013971,0.163416,0.198496,NaN,0.115324,NaN
Order Item Cardprod Id,-0.000859,-0.000431,0.033161,0.236367,0.001490,0.991092,0.228039,0.003173,0.906117,0.002031,...,-0.312555,0.238789,0.236367,0.033161,-0.005658,1.000000,0.991092,NaN,0.480288,NaN
Order Item Discount,0.002231,0.002897,0.064756,0.498734,-0.000750,0.140180,0.038490,-0.001861,0.144617,-0.002997,...,0.065379,0.617438,0.498734,0.064756,0.003921,0.147294,0.140180,NaN,0.488101,NaN
Order Item Discount Rate,0.001467,0.000065,-0.018644,-0.119469,0.000404,0.000572,0.001712,-0.000135,0.000255,-0.003889,...,-0.000028,0.000346,-0.119469,-0.018644,0.002691,0.000731,0.000572,NaN,0.000345,NaN
Order Item Id,-0.001769,-0.001848,0.013556,0.078176,-0.001376,0.186796,0.191814,-0.001208,0.101676,-0.003058,...,-0.083643,0.079002,0.078176,0.013556,0.013867,0.154077,0.186796,NaN,0.112448,NaN
Order Item Product Price,0.002185,0.006912,0.103459,0.781781,-0.002175,0.461059,0.111118,0.002191,0.446743,0.000471,...,-0.476232,0.789948,0.781781,0.103459,-0.000121,0.480288,0.461059,NaN,1.000000,NaN
Order Item Profit Ratio,-0.004638,-0.001822,0.823689,-0.001439,-0.002316,-0.001614,-0.000337,0.003364,-0.003044,-0.000081,...,0.001128,-0.001766,-0.001439,0.823689,-0.005650,-0.001784,-0.001614,NaN,-0.002043,NaN
Order Item Quantity,-0.000811,-0.002925,0.015696,0.105413,-0.000139,-0.302408,-0.091328,-0.006174,-0.265437,-0.001853,...,1.000000,0.106442,0.105413,0.015696,0.001662,-0.312555,-0.302408,NaN,-0.476232,NaN
Sales,0.001962,0.006327,0.131816,0.989744,-0.003564,0.227483,0.060961,-0.001490,0.234718,-0.000696,...,0.106442,1.000000,0.989744,0.131816,0.000564,0.238789,0.227483,NaN,0.789948,NaN
Order Item Total,0.001757,0.006445,0.133484,1.000000,-0.003791,0.225201,0.060181,-0.001304,0.232367,-0.000223,...,0.105413,0.989744,1.000000,0.133484,-0.000138,0.236367,0.225201,NaN,0.781781,NaN
Order Profit Per Order,-0.005101,-0.000185,1.000000,0.133484,-0.003727,0.031889,0.009354,0.002235,0.031442,0.000338,...,0.015696,0.131816,0.133484,1.000000,-0.004978,0.033161,0.031889,NaN,0.103459,NaN
Order Zipcode,-0.000811,0.005249,-0.004978,-0.000138,-0.014131,-0.005943,-0.005659,0.011843,-0.005982,-0.002921,...,0.001662,0.000564,-0.000138,-0.004978,1.000000,-0.005658,-0.005943,NaN,-0.000121,NaN
Product Card Id,-0.000859,-0.000431,0.033161,0.236367,0.001490,0.991092,0.228039,0.003173,0.906117,0.002031,...,-0.312555,0.238789,0.236367,0.033161,-0.005658,1.000000,0.991092,NaN,0.480288,NaN
Product Category Id,-0.000348,-0.000367,0.031889,0.225201,0.001752,1.000000,0.274633,0.002898,0.888835,0.002195,...,-0.302408,0.227483,0.225201,0.031889,-0.005943,0.991092,1.000000,NaN,0.461059,NaN
Product Description,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Product Price,0.002185,0.006912,0.103459,0.781781,-0.002175,0.461059,0.111118,0.002191,0.446743,0.000471,...,-0.476232,0.789948,0.781781,0.103459,-0.000121,0.480288,0.461059,NaN,1.000000,NaN
Product Status,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Sorting Data Based on Requirement

In [9]:
# Dropping columns which doesnt seem to be necessary for the analysis
col_dropped=['Days for shipping (real)', 'Days for shipment (scheduled)',
       'Sales per customer','Category Id','Customer Fname','Customer Lname','Customer City','Customer Email',
       'Customer Password','Customer State', 'Customer Street', 'Customer Zipcode',
       'Department Id','Latitude', 'Longitude','Order Item Discount',
       'Order City','Order Customer Id','Order Id', 'Order Item Cardprod Id',
       'Order Item Id','Order Item Profit Ratio','Order Profit Per Order',
       'Order Item Quantity','Order Item Total','Order State',
       'Order Zipcode', 'Product Card Id', 'Product Category Id',
       'Product Description', 'Product Image','Product Price',
       'Product Status']
ds.drop(col_dropped,axis=1,inplace=True)

# Confirming the remaining names of columns after dropping the unnecessary
ds.columns

Index(['Type', 'Benefit per order', 'Delivery Status', 'Late_delivery_risk',
       'Category Name', 'Customer Country', 'Customer Id', 'Customer Segment',
       'Department Name', 'Market', 'Order Country', 'order date (DateOrders)',
       'Order Item Discount Rate', 'Order Item Product Price', 'Sales',
       'Order Region', 'Order Status', 'Product Name',
       'shipping date (DateOrders)', 'Shipping Mode'],
      dtype='object')

In [10]:
# Formatting the date's columns
date_cols = ['order date (DateOrders)', 'shipping date (DateOrders)']
for col in date_cols:
    ds[col] = pd.to_datetime(ds[col])

## Reading and Understanding the Data:

### Initial Exploration on Data:

In [11]:
#Checking for null values
ds.isnull().sum()

Type                          0
Benefit per order             0
Delivery Status               0
Late_delivery_risk            0
Category Name                 0
Customer Country              0
Customer Id                   0
Customer Segment              0
Department Name               0
Market                        0
Order Country                 0
order date (DateOrders)       0
Order Item Discount Rate      0
Order Item Product Price      0
Sales                         0
Order Region                  0
Order Status                  0
Product Name                  0
shipping date (DateOrders)    0
Shipping Mode                 0
dtype: int64

In [12]:
# Observing the statistical characteristics of the dataset 
ds.describe()

,Benefit per order,Late_delivery_risk,Customer Id,Order Item Discount Rate,Order Item Product Price,Sales
count,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000
mean,21.974989,0.548291,6691.379495,0.101668,141.232550,203.772096
std,104.433526,0.497664,4162.918106,0.070415,139.732492,132.273077
min,-4274.979980,0.000000,1.000000,0.000000,9.990000,9.990000
25%,7.000000,0.000000,3258.500000,0.040000,50.000000,119.980003
50%,31.520000,1.000000,6457.000000,0.100000,59.990002,199.919998
75%,64.800003,1.000000,9779.000000,0.160000,199.990005,299.950012
max,911.799988,1.000000,20757.000000,0.250000,1999.989990,1999.989990

In [13]:
#Checking for duplicate
ds.duplicated().sum()

0

In [14]:
# Check for the number of rows and columns in the dataset
ds.shape

(180519, 20)

### Checking Value Counts of Each Column to understand the columns in depth

In [15]:
# Payment Type
ds['Type'].value_counts()

DEBIT       69295
TRANSFER    49883
PAYMENT     41725
CASH        19616
Name: Type, dtype: int64

In [16]:
# Benefit per Order
ds['Benefit per order'].value_counts()

 0.000000      1177
 143.990005     199
 72.000000      194
 46.799999      188
 24.000000      181
               ...
-48.830002        1
 48.220001        1
-145.729996       1
-330.109985       1
-337.100006       1
Name: Benefit per order, Length: 21998, dtype: int64

In [17]:
# Creating a bracket to determine profit and loss
d = ds['Benefit per order']
BenefitBracket = np.where(d < 0, 'Loss',
                np.where(d == 0, 'No Profit No Loss',
                         np.where(d > 0, 'Profit', np.nan)))

ds["BenefitBracket"] = pd.Categorical(BenefitBracket,
                            categories=['Loss', 'No Profit No Loss', 'Profit'],
                            ordered=True)

ds.head()

,Type,Benefit per order,Delivery Status,Late_delivery_risk,Category Name,Customer Country,Customer Id,Customer Segment,Department Name,Market,...,order date (DateOrders),Order Item Discount Rate,Order Item Product Price,Sales,Order Region,Order Status,Product Name,shipping date (DateOrders),Shipping Mode,BenefitBracket
0,DEBIT,91.250000,Advance shipping,0,Sporting Goods,Puerto Rico,20755,Consumer,Fitness,Pacific Asia,...,2018-01-31 22:56:00,0.04,327.75,327.75,Southeast Asia,COMPLETE,Smart watch,2018-02-03 22:56:00,Standard Class,Profit
1,TRANSFER,-249.089996,Late delivery,1,Sporting Goods,Puerto Rico,19492,Consumer,Fitness,Pacific Asia,...,2018-01-13 12:27:00,0.05,327.75,327.75,South Asia,PENDING,Smart watch,2018-01-18 12:27:00,Standard Class,Loss
2,CASH,-247.779999,Shipping on time,0,Sporting Goods,EE. UU.,19491,Consumer,Fitness,Pacific Asia,...,2018-01-13 12:06:00,0.06,327.75,327.75,South Asia,CLOSED,Smart watch,2018-01-17 12:06:00,Standard Class,Loss
3,DEBIT,22.860001,Advance shipping,0,Sporting Goods,EE. UU.,19490,Home Office,Fitness,Pacific Asia,...,2018-01-13 11:45:00,0.07,327.75,327.75,Oceania,COMPLETE,Smart watch,2018-01-16 11:45:00,Standard Class,Profit
4,PAYMENT,134.210007,Advance shipping,0,Sporting Goods,Puerto Rico,19489,Corporate,Fitness,Pacific Asia,...,2018-01-13 11:24:00,0.09,327.75,327.75,Oceania,PENDING_PAYMENT,Smart watch,2018-01-15 11:24:00,Standard Class,Profit

In [18]:
# Delivery Status
ds['Delivery Status'].value_counts()

Late delivery        98977
Advance shipping     41592
Shipping on time     32196
Shipping canceled     7754
Name: Delivery Status, dtype: int64

In [19]:
# Risk of Late Delivery
ds['Late_delivery_risk'].value_counts()

1    98977
0    81542
Name: Late_delivery_risk, dtype: int64

In [20]:
# Category Name
ds['Category Name'].value_counts()

Cleats                  24551
Men's Footwear          22246
Women's Apparel         21035
Indoor/Outdoor Games    19298
Fishing                 17325
Water Sports            15540
Camping & Hiking        13729
Cardio Equipment        12487
Shop By Sport           10984
Electronics              3156
Accessories              1780
Golf Balls               1475
Girls' Apparel           1201
Golf Gloves              1070
Trade-In                  974
Video Games               838
Children's Clothing       652
Women's Clothing          650
Baseball & Softball       632
Hockey                    614
Cameras                   592
Toys                      529
Golf Shoes                524
Pet Supplies              492
Garden                    484
Crafts                    484
DVDs                      483
Computers                 442
Golf Apparel              441
Hunting & Shooting        440
Music                     434
Consumer Electronics      431
Boxing & MMA              423
Books                     405
Kids' Golf Clubs          384
Health and Beauty         362
Sporting Goods            357
Lacrosse                  343
Tennis & Racquet          328
Fitness Accessories       309
Men's Golf Clubs          283
CDs                       271
Men's Clothing            208
Baby                      207
Women's Golf Clubs        181
Soccer                    138
Strength Training         111
As Seen on  TV!            68
Basketball                 67
Golf Bags & Carts          61
Name: Category Name, dtype: int64

In [21]:
# Customer's Country
ds['Customer Country'].value_counts()

EE. UU.        111146
Puerto Rico     69373
Name: Customer Country, dtype: int64

In [22]:
# Customer's Segment
ds['Customer Segment'].value_counts()

Consumer       93504
Corporate      54789
Home Office    32226
Name: Customer Segment, dtype: int64

In [23]:
# Product Department Name
ds['Department Name'].value_counts()

Fan Shop              66861
Apparel               48998
Golf                  33220
Footwear              14525
Outdoors               9686
Fitness                2479
Discs Shop             2026
Technology             1465
Pet Shop                492
Book Shop               405
Health and Beauty       362
Name: Department Name, dtype: int64

In [24]:
# Sales Market
ds['Market'].value_counts()

LATAM           51594
Europe          50252
Pacific Asia    41260
USCA            25799
Africa          11614
Name: Market, dtype: int64

In [25]:
# Order Country
ds['Order Country'].value_counts()

Estados Unidos       24840
Francia              13222
MÃ©xico               13172
Alemania              9564
Australia             8497
                     ...
Guinea Ecuatorial        2
Kuwait                   2
SÃ¡hara Occidental        2
Burundi                  1
Serbia                   1
Name: Order Country, Length: 164, dtype: int64

In [26]:
# Date of Order
ds['order date (DateOrders)'].value_counts()

2016-12-14 12:29:00    5
2015-02-22 14:38:00    5
2016-02-17 14:08:00    5
2016-12-31 09:50:00    5
2016-02-11 16:35:00    5
                      ..
2016-09-05 05:58:00    1
2016-09-06 01:56:00    1
2016-09-06 03:20:00    1
2016-09-06 19:27:00    1
2016-01-17 05:56:00    1
Name: order date (DateOrders), Length: 65752, dtype: int64

In [27]:
# Discount rate of the ordered Item
ds['Order Item Discount Rate'].value_counts()

0.04    10029
0.15    10029
0.25    10029
0.20    10029
0.18    10029
0.17    10029
0.05    10029
0.16    10029
0.13    10029
0.12    10029
0.10    10029
0.09    10029
0.07    10029
0.06    10029
0.03    10029
0.00    10028
0.01    10028
0.02    10028
Name: Order Item Discount Rate, dtype: int64

In [28]:
# # Range for the Order Discount Rates 
d = ds['Order Item Discount Rate']
OrdDiscBracket = np.where(d <= 0.10, '<10%',
                np.where(d <= 0.20, '<20%',
                         np.where(d > 0.20, '>20%', np.nan)))

ds["Order Item Discount Bracket"] = pd.Categorical(OrdDiscBracket,
                            categories=['<10%', '<20%', '>20%'],
                            ordered=True)

ds.head()

,Type,Benefit per order,Delivery Status,Late_delivery_risk,Category Name,Customer Country,Customer Id,Customer Segment,Department Name,Market,...,Order Item Discount Rate,Order Item Product Price,Sales,Order Region,Order Status,Product Name,shipping date (DateOrders),Shipping Mode,BenefitBracket,Order Item Discount Bracket
0,DEBIT,91.250000,Advance shipping,0,Sporting Goods,Puerto Rico,20755,Consumer,Fitness,Pacific Asia,...,0.04,327.75,327.75,Southeast Asia,COMPLETE,Smart watch,2018-02-03 22:56:00,Standard Class,Profit,<10%
1,TRANSFER,-249.089996,Late delivery,1,Sporting Goods,Puerto Rico,19492,Consumer,Fitness,Pacific Asia,...,0.05,327.75,327.75,South Asia,PENDING,Smart watch,2018-01-18 12:27:00,Standard Class,Loss,<10%
2,CASH,-247.779999,Shipping on time,0,Sporting Goods,EE. UU.,19491,Consumer,Fitness,Pacific Asia,...,0.06,327.75,327.75,South Asia,CLOSED,Smart watch,2018-01-17 12:06:00,Standard Class,Loss,<10%
3,DEBIT,22.860001,Advance shipping,0,Sporting Goods,EE. UU.,19490,Home Office,Fitness,Pacific Asia,...,0.07,327.75,327.75,Oceania,COMPLETE,Smart watch,2018-01-16 11:45:00,Standard Class,Profit,<10%
4,PAYMENT,134.210007,Advance shipping,0,Sporting Goods,Puerto Rico,19489,Corporate,Fitness,Pacific Asia,...,0.09,327.75,327.75,Oceania,PENDING_PAYMENT,Smart watch,2018-01-15 11:24:00,Standard Class,Profit,<10%

In [29]:
# Product Price
ds['Order Item Product Price'].value_counts()

59.990002      24820
129.990005     22372
50.000000      21035
49.980000      19298
399.980011     17325
               ...
349.989990        40
329.989990        27
599.989990        21
1999.989990       15
999.989990        10
Name: Order Item Product Price, Length: 75, dtype: int64

In [30]:
# Range for the Product Price
ProdPrice_brackets = [0, 500, 1000, 1500, 2000]
ProdPrice_labels = ['<500', '500-1000', '1000-1500', '1500-2000']

# Assign salary brackets to dataset
ds['Product Price Bracket'] = pd.cut(ds['Order Item Product Price'], bins=ProdPrice_brackets, labels=ProdPrice_labels)

# View the updated dataset
ds.head()

,Type,Benefit per order,Delivery Status,Late_delivery_risk,Category Name,Customer Country,Customer Id,Customer Segment,Department Name,Market,...,Order Item Product Price,Sales,Order Region,Order Status,Product Name,shipping date (DateOrders),Shipping Mode,BenefitBracket,Order Item Discount Bracket,Product Price Bracket
0,DEBIT,91.250000,Advance shipping,0,Sporting Goods,Puerto Rico,20755,Consumer,Fitness,Pacific Asia,...,327.75,327.75,Southeast Asia,COMPLETE,Smart watch,2018-02-03 22:56:00,Standard Class,Profit,<10%,<500
1,TRANSFER,-249.089996,Late delivery,1,Sporting Goods,Puerto Rico,19492,Consumer,Fitness,Pacific Asia,...,327.75,327.75,South Asia,PENDING,Smart watch,2018-01-18 12:27:00,Standard Class,Loss,<10%,<500
2,CASH,-247.779999,Shipping on time,0,Sporting Goods,EE. UU.,19491,Consumer,Fitness,Pacific Asia,...,327.75,327.75,South Asia,CLOSED,Smart watch,2018-01-17 12:06:00,Standard Class,Loss,<10%,<500
3,DEBIT,22.860001,Advance shipping,0,Sporting Goods,EE. UU.,19490,Home Office,Fitness,Pacific Asia,...,327.75,327.75,Oceania,COMPLETE,Smart watch,2018-01-16 11:45:00,Standard Class,Profit,<10%,<500
4,PAYMENT,134.210007,Advance shipping,0,Sporting Goods,Puerto Rico,19489,Corporate,Fitness,Pacific Asia,...,327.75,327.75,Oceania,PENDING_PAYMENT,Smart watch,2018-01-15 11:24:00,Standard Class,Profit,<10%,<500

In [31]:
# Sales
ds['Sales'].value_counts()

129.990005    22372
399.980011    17325
199.990005    15622
299.980011    13729
179.970001     5016
              ...
999.989990       10
379.959992       10
198.000000        9
396.000000        9
99.000000         9
Name: Sales, Length: 193, dtype: int64

In [32]:
# # Range for the Sales
Sales_brackets = [0, 500, 1000, 1500, 2000]
Sales_labels = ['<500', '500-1000', '1000-1500', '1500-2000']

# Assign salary brackets to dataset
ds['Sales Bracket'] = pd.cut(ds['Sales'], bins=Sales_brackets, labels=Sales_labels)

# View the updated dataset
ds.head()

,Type,Benefit per order,Delivery Status,Late_delivery_risk,Category Name,Customer Country,Customer Id,Customer Segment,Department Name,Market,...,Sales,Order Region,Order Status,Product Name,shipping date (DateOrders),Shipping Mode,BenefitBracket,Order Item Discount Bracket,Product Price Bracket,Sales Bracket
0,DEBIT,91.250000,Advance shipping,0,Sporting Goods,Puerto Rico,20755,Consumer,Fitness,Pacific Asia,...,327.75,Southeast Asia,COMPLETE,Smart watch,2018-02-03 22:56:00,Standard Class,Profit,<10%,<500,<500
1,TRANSFER,-249.089996,Late delivery,1,Sporting Goods,Puerto Rico,19492,Consumer,Fitness,Pacific Asia,...,327.75,South Asia,PENDING,Smart watch,2018-01-18 12:27:00,Standard Class,Loss,<10%,<500,<500
2,CASH,-247.779999,Shipping on time,0,Sporting Goods,EE. UU.,19491,Consumer,Fitness,Pacific Asia,...,327.75,South Asia,CLOSED,Smart watch,2018-01-17 12:06:00,Standard Class,Loss,<10%,<500,<500
3,DEBIT,22.860001,Advance shipping,0,Sporting Goods,EE. UU.,19490,Home Office,Fitness,Pacific Asia,...,327.75,Oceania,COMPLETE,Smart watch,2018-01-16 11:45:00,Standard Class,Profit,<10%,<500,<500
4,PAYMENT,134.210007,Advance shipping,0,Sporting Goods,Puerto Rico,19489,Corporate,Fitness,Pacific Asia,...,327.75,Oceania,PENDING_PAYMENT,Smart watch,2018-01-15 11:24:00,Standard Class,Profit,<10%,<500,<500

In [33]:
# Region of the order
ds['Order Region'].value_counts()

Central America    28341
Western Europe     27109
South America      14935
Oceania            10148
Northern Europe     9792
Southeast Asia      9539
Southern Europe     9431
Caribbean           8318
West of USA         7993
South Asia          7731
Eastern Asia        7280
East of USA         6915
West Asia           6009
US Center           5887
South of  USA       4045
Eastern Europe      3920
West Africa         3696
North Africa        3232
East Africa         1852
Central Africa      1677
Southern Africa     1157
Canada               959
Central Asia         553
Name: Order Region, dtype: int64

In [34]:
# Order Status
ds['Order Status'].value_counts()

COMPLETE           59491
PENDING_PAYMENT    39832
PROCESSING         21902
PENDING            20227
CLOSED             19616
ON_HOLD             9804
SUSPECTED_FRAUD     4062
CANCELED            3692
PAYMENT_REVIEW      1893
Name: Order Status, dtype: int64

In [35]:
# Name of the Product
ds['Product Name'].value_counts()

Perfect Fitness Perfect Rip Deck                 24515
Nike Men's CJ Elite 2 TD Football Cleat          22246
Nike Men's Dri-FIT Victory Golf Polo             21035
O'Brien Men's Neoprene Life Vest                 19298
Field & Stream Sportsman 16 Gun Fire Safe        17325
                                                 ...
Stiga Master Series ST3100 Competition Indoor       27
SOLE E35 Elliptical                                 15
Bushnell Pro X7 Jolt Slope Rangefinder              11
Bowflex SelectTech 1090 Dumbbells                   10
SOLE E25 Elliptical                                 10
Name: Product Name, Length: 118, dtype: int64

In [36]:
# Date of shipping
ds['shipping date (DateOrders)'].value_counts()

2016-01-05 05:58:00    10
2015-07-16 10:14:00    10
2015-04-17 22:16:00    10
2015-05-27 06:48:00    10
2015-05-09 18:02:00    10
                       ..
2015-03-29 18:06:00     1
2015-04-02 12:40:00     1
2015-04-02 23:10:00     1
2015-03-31 07:03:00     1
2016-01-21 05:56:00     1
Name: shipping date (DateOrders), Length: 63701, dtype: int64

In [37]:
# Mode of shipping
ds['Shipping Mode'].value_counts()

Standard Class    107752
Second Class       35216
First Class        27814
Same Day            9737
Name: Shipping Mode, dtype: int64

## Exporting the Cleaned Dataset as a New CSV

In [38]:
# Writing the Cleaned Data to CSV
ds.to_csv('Cleaned_DataCoSupplyChainDataset.csv',index=False)

In [39]:
# Displaying First Five values of the Cleaned Dataset
ds.head()

,Type,Benefit per order,Delivery Status,Late_delivery_risk,Category Name,Customer Country,Customer Id,Customer Segment,Department Name,Market,...,Sales,Order Region,Order Status,Product Name,shipping date (DateOrders),Shipping Mode,BenefitBracket,Order Item Discount Bracket,Product Price Bracket,Sales Bracket
0,DEBIT,91.250000,Advance shipping,0,Sporting Goods,Puerto Rico,20755,Consumer,Fitness,Pacific Asia,...,327.75,Southeast Asia,COMPLETE,Smart watch,2018-02-03 22:56:00,Standard Class,Profit,<10%,<500,<500
1,TRANSFER,-249.089996,Late delivery,1,Sporting Goods,Puerto Rico,19492,Consumer,Fitness,Pacific Asia,...,327.75,South Asia,PENDING,Smart watch,2018-01-18 12:27:00,Standard Class,Loss,<10%,<500,<500
2,CASH,-247.779999,Shipping on time,0,Sporting Goods,EE. UU.,19491,Consumer,Fitness,Pacific Asia,...,327.75,South Asia,CLOSED,Smart watch,2018-01-17 12:06:00,Standard Class,Loss,<10%,<500,<500
3,DEBIT,22.860001,Advance shipping,0,Sporting Goods,EE. UU.,19490,Home Office,Fitness,Pacific Asia,...,327.75,Oceania,COMPLETE,Smart watch,2018-01-16 11:45:00,Standard Class,Profit,<10%,<500,<500
4,PAYMENT,134.210007,Advance shipping,0,Sporting Goods,Puerto Rico,19489,Corporate,Fitness,Pacific Asia,...,327.75,Oceania,PENDING_PAYMENT,Smart watch,2018-01-15 11:24:00,Standard Class,Profit,<10%,<500,<500

In [40]:
# Displaying Columns of the Cleaned Dataset
ds.columns

Index(['Type', 'Benefit per order', 'Delivery Status', 'Late_delivery_risk',
       'Category Name', 'Customer Country', 'Customer Id', 'Customer Segment',
       'Department Name', 'Market', 'Order Country', 'order date (DateOrders)',
       'Order Item Discount Rate', 'Order Item Product Price', 'Sales',
       'Order Region', 'Order Status', 'Product Name',
       'shipping date (DateOrders)', 'Shipping Mode', 'BenefitBracket',
       'Order Item Discount Bracket', 'Product Price Bracket',
       'Sales Bracket'],
      dtype='object')

In [41]:
# Shape of the Cleaned Dataset
ds.shape

(180519, 24)

In [42]:
# Checking for Duplicates in the Cleaned Dataset
ds.duplicated().sum()

0